inbound-transport:
    - [acapy_plugin_toolbox.http_ws, 0.0.0.0, 3000]
outbound-transport: http
endpoint:
    - http://localhost:3000
    - ws://localhost:3000
plugin:
  - acapy_plugin_toolbox
no-ledger: true
admin: [0.0.0.0, 3001]
admin-insecure-mode: true
debug-connections: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true
connections-invite: true
label: Aries Cloud Agent + Toolbox Plugin
invite-label: ACA-Py (Admin)
invite-metadata-json: '{"group": "admin"}'
preserve-exchange-records: true
auto-store-credential: true
auto-respond-credential-proposal: true
auto-respond-credential-offer: true
auto-respond-credential-request: true
auto-respond-presentation-proposal: true
auto-respond-presentation-request: true
auto-verify-presentation: true
