label: Alice
invite-label: Alice (Admin)
wallet-name: alice
endpoint:
  - http://localhost:3000
  - ws://localhost:3000
inbound-transport:
  - [acapy_plugin_toolbox.http_ws, 0.0.0.0, 3000]
admin: [0.0.0.0, 3001]

# Load toolbox plugin
plugin:
  - acapy_plugin_toolbox

# Transport
outbound-transport: http

# Ledger
# Use Indicio TestNet. Become an endorser at https://selfserve.indiciotech.io/.
genesis-url: https://raw.githubusercontent.com/Indicio-tech/indicio-network/master/genesis_files/pool_transactions_testnet_genesis

# Admin
admin-insecure-mode: true

# Connections
debug-connections: true
debug-credentials: true
debug-presentations: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true
connections-invite: true
invite-metadata-json: '{"group": "admin"}'

# Credentials and Presentations
preserve-exchange-records: true
auto-store-credential: true
auto-respond-credential-proposal: true
auto-respond-credential-offer: true
auto-respond-credential-request: true

auto-respond-presentation-proposal: true
auto-respond-presentation-request: true
auto-verify-presentation: true

tails-server-base-url: http://tails-server:6543

# Wallet
wallet-type: indy
wallet-key: "insecure, for use in demo only"
auto-provision: true

# Enable undelivered queue
# Important for communication with toolbox over http (as opposed to ws)
enable-undelivered-queue: true
