label: Aries Cloud Agent + Toolbox Plugin

# Admin
admin: [0.0.0.0, 3001]
admin-insecure-mode: true

# Load toolbox plugin
plugin:
  - acapy_plugin_toolbox

# Transport
inbound-transport:
  - [acapy_plugin_toolbox.http_ws, 0.0.0.0, 3000]
outbound-transport: http
endpoint:
  - http://localhost:3000
  - ws://localhost:3000

# Ledger
# Use Sovrin Builder Net. Become an endorser at https://selfserve.sovrin.org.
genesis-url: https://raw.githubusercontent.com/sovrin-foundation/sovrin/master/sovrin/pool_transactions_builder_genesis

# Connections
debug-connections: true
debug-credentials: true
debug-presentations: true
auto-accept-invites: true
auto-accept-requests: true
auto-ping-connection: true

# Generate Admin Invitation
connections-invite: true
invite-label: ACA-Py (Admin)
invite-metadata-json: '{"group": "admin"}'

# Credentials and Presentations
preserve-exchange-records: true
auto-store-credential: true
auto-respond-credential-proposal: true
auto-respond-credential-offer: true
auto-respond-credential-request: true

auto-respond-presentation-proposal: true
auto-respond-presentation-request: true
auto-verify-presentation: true

# Wallet
wallet-name: default
wallet-type: indy
wallet-key: "insecure, for use in demo only"
auto-provision: true

# Enable undelivered queue
# Important for communication with toolbox over http (as opposed to ws)
enable-undelivered-queue: true
